# Generated by Django 4.1.7 on 2023-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('owner', models.CharField(max_length=50)),
                ('vehicle', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('amount', models.IntegerField(max_length=50)),
            ],
        ),
    ]
